
<div style='padding:5px; text-align:center;'>
	Enter your email address and password below. <br />If you do not have an account please contact your system administrator.<br /><br />
</div>
<div style='margin:auto;padding:20px; width:320px;  height: 170px;' class='toolbar'>
<form method='post' action=''>
	<table>
		<tr>
			<td>
			Email Address: <input type='text' name='email' style='width:300px;'>
			</td>
			</tr>
			<tr>
			<td>
			Password: <input type='password' name='password' style='width:300px;'>
			</td>
		</tr>
	</table>

	<center>
		<input type='submit' value='Log In'>
		
	</center>
	</form>

</div>