<div style='padding:10px;'>
<?php if ($this->pageCount): ?>
<div class="paginationControl" style='float:right;'>
<!-- Previous page link -->
<?php if (isset($this->previous)): ?>
	<a href="<?= $this->url(array('page' => $this->previous)); ?><? if(isset($_GET['term'])){ echo "?term=".$_GET['term']; }?>">&lt; Previous</a> |
<?php else: ?>
	<span class="disabled">&lt; Previous</span> |
<?php endif; ?>

<!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page): ?>
	<?php if ($page != $this->current): ?>
		<a href="<?= $this->url(array('page' => $page)); ?><? if(isset($_GET['term'])){ echo "?term=".$_GET['term']; }?>"><?= $page; ?></a> |
	<?php else: ?>
		<?= $page; ?> |
	<?php endif; ?>
<?php endforeach; ?>

<!-- Next page link -->
<?php if (isset($this->next)): ?>
	<a href="<?= $this->url(array('page' => $this->next)); ?><? if(isset($_GET['term'])){ echo "?term=".$_GET['term']; }?>">Next &gt;</a>
<?php else: ?>
	<span class="disabled">Next &gt;</span>
<?php endif; ?>
 Total Results: <?=$this->totalItemCount;?>
</div>
<br style='clear:both;'>
<?php endif; ?>
</div>