<?php
$method = $this->method;
$totalData = $this->totalData;
?>
<?php if ($method == 'html' || $method == 'pdf') { ?>
    <style type='text/css'>
        #page{
            font-family: Arial, sans-serif;
        }
    </style>
    <div id='page'>

        <table style='width:100%;'>
            <tr>
                <td>
                    <h1>Data Verification (<?php if ($this->start && $this->end) { ?><?php echo date('M d, Y', strtotime($this->start)); ?> - <?php echo date('M d, Y', strtotime($this->end)); ?><?php } else { ?><?php echodate('M Y', strtotime($this->start)); ?><?php } ?>)</h1>
                </td>
                <?php if ($method == 'pdf') { ?>
                    <td style='text-align:right;'><img style='height:80px;' src="<?php echo APPLICATION_PATH . "/../public/images/logo.png"; ?>"></td>
                <?php } ?> 
            </tr>
        </table>
        <?php 
            $lineBreakFlag = false;
            foreach ($totalData AS $key => $data) { 
        ?>
            <?php if (count($data['records']) > 0) { ?>
                <?php 
                    if($lineBreakFlag == true){
                        echo '<p style="page-break-after:always;"></p>';
                    }
                    $lineBreakFlag = true;
                ?>
                <br />                
                <div style='border:1px solid #000; padding:5px; background:#6a6a6a; color:#fff;'>
                    <table>
                        <tr>

                            <td><spamn style='font-size:18px;'><?php echo $data['employee']['lastname']; ?>, <?php echo $data['employee']['firstname']; ?></span></td>
                            <td style='padding-left:15px;'>ID: <?php echo $data['employee']['cp_id']; ?></td>
                            </tr>
                    </table>
                </div>
                <table width='100%' style='border-collapse:collapse; background: #fff;' border='1'>
                    <tr style='background: #000; color:#fff;'>
                        <td>Date</td>
                        <td>Reason</td>
                        <td>Emp %</td>
                        <td>Substitute</td>
                        <td>Location</td>
                    </tr>
                    <?php foreach ($data['records'] AS $record) { ?>
                        <tr>
                            <td><?php echo $record->date; ?></td>
                            <td><?php echo $record->reason; ?><?php
                                if ($record->reason == 'Other - EXPLAIN') {
                                    echo " : " . $record->notes;
                                }
                                ?></td>
                            <td><?php echo $record->percent; ?></td>
                            <td><?php echo $this->substituteName($record->substitute); ?></td>
                            <td><?php echo $this->locationName($record->location); ?></td>
                        </tr>
                <?php } ?>
                </table>                
        <?php } ?>
    <?php } ?>
    </div>	


    <?php
}

if ($method == 'csv') {
    $csv = "";
    $csv .="Date,ID,Last Name,First Name,Reason,Emp %,SubLast,SubFirst,Location\n";
    foreach ($totalData AS $data) {
        if (count($data['records']) > 0) {


            foreach ($data['records'] AS $record) {

                $csv .= $record->date . ",";
                $csv .= $data['employee']['cp_id'] . ",";
                $csv .= $data['employee']['lastname'] . ",";
                $csv .= $data['employee']['firstname'] . ",";
                $csv .= $record->reason;
                if ($record->reason == 'Other - EXPLAIN') {
                    $csv .= " : " . str_replace(",", "", $record->notes) . ",";
                } else {
                    $csv .= ",";
                }
                $csv .= $record->percent . ",";
                $csv .= $this->substituteName($record->substitute) . ",";
                $csv .= $this->locationName($record->location);
                $csv .= "\n";
            }
        }
    }

    header('Content-Type: application/csv');
    header('Content-Disposition: attachment; filename=Data-Verification-' . date('M Y', strtotime($this->start)) . "-" . date('Y-m-d') . "." . $method);
    header('Pragma: no-cache');
    echo $csv;
}