<h1>Reports</h1>
<? if($this->user->admin == 1){ ?>
	<div class='howto'>
		<h2 style='margin:0;'>Export CSV</h2><br />
		Select your criteria below. Ignore any fields you do not want included.
		<br /><br />
		<form method='post' action='/exportcsv'>
		<table>
			<tr>
				<?  
					$i=1;
				foreach($this->columns AS $column){ ?>
				<? if($column <> 'date_created' && $column <> 'notes' && $column <> 'id' && $column <> 'payrate' && $column <> 'acct_two' && $column <> 'percent_two'){ ?>
					<td><?=ucwords(str_replace("_"," ",$column));?></td>
					<td style='padding-right:20px; text-align:right;'>
					
						<? if($column <> 'date' && $column <> 'id'){ ?>
						
							<select name='<?=$column;?>' style='width:200px;'>
								<option value="">Select <?=ucwords(str_replace("_"," ",$column));?></option>
								<? foreach($this->columnValues[$column] AS $value){ ?>
									<? if($column == 'user'){ ?>
									<option value="<?=$value->{$column};?>"><?=$this->userName($value->{$column});?></option>
									<? } else if($column == 'substitute') { ?>
									<option value="<?=$value->{$column};?>"><?=$this->substituteName($value->{$column});?></option>
									<? } else if($column == 'location') { ?>
									<option value="<?=$value->{$column};?>"><?=$this->locationName($value->{$column});?></option>
									<? } else if($column =='employee') { ?>
									<option value="<?=$value->{$column};?>"><?=$this->employeeName($value->{$column});?></option>
									<? } else if($column == 'leave_form') { ?>
									<option value="<?=$value->{$column};?>"><? if($value->{$column} == 1){ echo "Yes"; } else if($value->{$column} === '0')   { echo "No"; } ?></option>
				
									<? } else { ?>
										<? if(trim($value->{$column}) <> ''){ ?>
											<option value="<?=$value->{$column};?>"><?=$value->{$column};?></option>
										<? } ?>
									<? } ?>
									
								<? } ?>
							</select>
						<? } else { ?>
						<? if($column == 'date'){ ?>
							<input type='text' name='start_date' style='width:85px;' class='small datepicker' placeholder="Start">
							<input type='text' name='end_date' style='width:85px;' class='small datepicker' placeholder="End">
							<? } else { ?>
							<input type='text' name='<?=$column;?>' style='width:100px;' class='small <? if($column == 'date'){ echo 'datepicker'; } ?>'>
							<? } ?>
						<? } ?>
				
					</td>
					<? if($i == 3){ ?>
						</tr><tr>
					<? $i =0; } $i++; ?>
						<? } ?>
				<? } ?>
			</tr>
			
		</table>
		<table>
			<tr>
				<td style='text-align:right;' >Title Paid</td>
				<td style='padding-left:18px; text-align:right;' >					
					<select name='paid' style='width:200px;'>
							<option value="">Select One</option>
							<option value="Yes">Yes</option>
							<option value="No">No</option>
						</select>
					</td>									
			</tr>
		</table>
		<input type='submit' value='Export CSV' style='float:right;'>
		<br style='clear:both;'>
		</form>
	</div>
<? } ?>
<div class='howto'>
	Below you'll find links to different reports that will provide insights into your data.  All reports can either be viewed in the application, printed or downloaded as a CSV file for use in spreadsheet software such as Excel or Numbers.
</div>

<table class='zebra'>
		<tr style='background:#000; color:#fff;'>
		<td style='width:800px;'>Report Title</td>
		<td></td>
		<td style='text-align:center;'>View</td>
		<td style='text-align:center;'>Print</td>
		<td style='text-align:center;'>Excel</td>
	</tr>
	<tr>
		<td>

		Leave Statement
		
		</td><td>
		<script type='text/javascript'>
			function getLeaveStatement(type){
				var id = $('#leavestatement_employee').val();
				window.location.href = "/leavestatement/"+id+"/any/"+type;
			}
		</script>
		<select name='employee' id='leavestatement_employee' style='width:450px;'>
	
					<? 
						$location = 0;
					foreach($this->employees AS $employee){ 
						if($location <> $employee->location){ ?>
						<? if($location > 0){ ?>
							</optgroup>
							<? } ?>
							
							<optgroup label="<?=$this->locationName($employee->location);?>">
							
						<? 
							$location = $employee->location;
						}
					?>
							<option value="<?=$employee->id;?>"><?=$employee->lastname;?>, <?=$employee->firstname;?> (<?=$employee->position;?>)</option>
					<? } ?>
					</optgroup>
				</select>

		</td>
		<td style='text-align:center;'><a href="javascript:void(0);" onClick="getLeaveStatement('html');"><img src="/images/view.png"></a></td>
		<td style='text-align:center;'><a href="javascript:void(0);" onClick="getLeaveStatement('pdf');"><img src="/images/print.png"></a></td>
		<td style='text-align:center;'><a href="javascript:void(0);" onClick="getLeaveStatement('csv');"><img src="/images/excel.png"></a></td>
	</tr>
	<tr>
		<td style='width:800px;'>Monthly Data Entry Verification</td>
		<td>
		<script type='text/javascript'>
			function getDataVerification(type){
				var start = $('#verification_month').val();
                                var location = $('#verification_location').val();                                
				window.location.href = "/dataverification/"+start+"/"+(location?location:"any")+"/"+type;
			}
		</script>
			<select id='verification_month'>
				<?
					$start = date('Y-m-d',strtotime('+1 month'));
					$i = 0;
					while($i <= 13){
						$newDate = date('M Y',strtotime($start." - $i month"));
						echo "<option value='".date('Y-m-1',strtotime($newDate))."' ";
						if($i ==1){ echo "selected"; }
						echo ">".$newDate."</option>";
						$i++;
					}
				?>
			</select>
                        <?php if($this->user->admin == 1){?>
                             
                            &nbsp;&nbsp;
                            <select id='verification_location'>
                                <option value="">Any Location</option>
				<?php
                                    foreach($this->locations as $row){
                                        printf('<option value="%s">%s</option>', $row['id'], $row['name']);
                                    }
				?>
                            </select>
                        <?php }?>
		</td>
		<td style='text-align:center;'><a href="javascript:void(0);" onClick="getDataVerification('html');"><img src="/images/view.png"></a></td>
		<td style='text-align:center;'><a href="javascript:void(0);" onClick="getDataVerification('pdf');"><img src="/images/print.png"></a></td>
		<td style='text-align:center;'><a href="javascript:void(0);" onClick="getDataVerification('csv');"><img src="/images/excel.png"></a></td>
	</tr>
	<tr>
		<td>Monthly Data Entry Verification By Date</td>
		<td>
		<script type='text/javascript'>
			function getDataVerificationByDate(type){
				var start = $('#ver_start').val();
				var end = $('#ver_end').val();
				window.location.href = "/dataverification/"+start+"~"+end+"/any/"+type;
			}
		</script>
			<table>
			<tr style='background:none;'>
				<td>
					Start: 
				</td>
				<td>
					<input type='text' id="ver_start" class="datepicker" value="<?=date('Y-m-d',strtotime("1 month ago"));?>">
				</td>
			</tr>
			<tr style='background:none;'>
				<td>
					End: 
				</td>
				<td>
					<input type='text' id="ver_end" class="datepicker" value="<?=date('Y-m-d',strtotime("today"));?>">
				</td>
			</tr>
		</table>
		</td>
		<td style='text-align:center;'><a href="javascript:void(0);" onClick="getDataVerificationByDate('html');"><img src="/images/view.png"></a></td>
		<td style='text-align:center;'><a href="javascript:void(0);" onClick="getDataVerificationByDate('pdf');"><img src="/images/print.png"></a></td>
		<td style='text-align:center;'><a href="javascript:void(0);" onClick="getDataVerificationByDate('csv');"><img src="/images/excel.png"></a></td>
	</tr>


</table>