<div class='toolbar' style='height:auto !important;'>
	<h1>New Employee</h1>
	<form method='post' action='' autocomplete='off'>
	<table>
		<tr>
			<td>First Name</td><td><input type='text' name='firstname' style='width:200px;' value="<?=@$this->data['firstname'];?>"></td>
			<td>Last Name</td><td><input type='text' name='lastname' style='width:200px;' value="<?=@$this->data['lastname'];?>"></td>
		</tr>
		<tr>
			<td>Location</td><td>
				<select name='location' style='width:200px;'>
					<? foreach($this->locations AS $location){ 
					if($this->user->location == $location->id){
														$selected = 'selected';
													} else {
														$selected = '';
													}
					?>
						<option value="<?=$location->id;?>" <?=$selected;?>><?=$location->name;?></option>
					<? } ?>
				</select>
			</td>
			<td style='text-align:right;'>Position</td><td><input type='text' name='position' style='width:200px;' value="<?=@$this->data['position'];?>"></td>
		</tr>
		<tr>
			<td>Acct #1</td>
			<td>
				<input type='text' name='account_number' class='account_number' style='width:280px;' value="<?=@$this->data['account_number'];?>">
			</td>
			<td style='text-align:right;'>ID </td>
			<td>
				<input type='text' name='cp_id' class='cp_id' style='width:200px;' value="<?=@$this->data['cp_id'];?>">
			</td>
		</tr>
		<tr>
			<td>Acct #2</td>
			<td>
				<input type='text' name='account_number_two' class='account_number_two' style='width:280px;' value="<?=@$this->data['account_number_two'];?>" >
			</td>
			<td style='text-align:right;'>Title Paid</td>
			<td>
				<select name='paid' style='width:200px;'>
					<option value="">Select One</option>
					<option value="Yes" <? if(@$this->data['paid'] == 'Yes'){ echo "selected"; } ?> >Yes</option>
					<option value="No" <? if(@$this->data['paid'] == 'No'){ echo "selected"; } ?> >No</option>
				</select>
			</td>
		</tr>
	</table>
	<br />
	<input type='hidden' name='method' value='create'>
	<input type='submit' value="Create Employee">
	
	</form>
</div>

 <?= $this->paginationControl($this->employees, 'Sliding', 'pagination_control.phtml'); ?>
 <div style='padding:0px; position:relative; top:-20px;'>
	<form method='get' action="/employees">
		<input type='text' name='term' style='width:200px;' value="<?=@$_GET['term'];?>" placeholder="Search...">
		<input type='submit' style='display:none;'>
	</form>
</div>
 	<table class='zebra'>
 		<tr style='background:#000; color:#fff;'>
 			<td>Name</td>
			<td>Location</td>
			<td>Position</td>
			<td>Acct</td>			
			<td>Title Paid</td>
			<td>ID</td>			
 			<td>Edit</td>
 		</tr>
 		<? foreach($this->employees AS $employee){ ?>
 			<tr id='view_row_<?=$employee->id;?>'>
 				<td><?=$employee->lastname;?>, <?=$employee->firstname;?></td>
				<td><?=$this->locationName($employee->location);?></td>
				<td><?=$employee->position;?></td>
				<td>
					<b>#1</b>&nbsp;&nbsp;<label class="jqAccount"><?=$employee->account_number;?></label>
					<? echo !empty($employee->account_number_two) ? '<br /> <b>#2</b>&nbsp;&nbsp;<label class="jqAccount">'.$employee->account_number_two.'</label>' : '';?>
				</td>				
				<td><?=$employee->paid;?></td>
				<td><?=$employee->cp_id;?></td>
 				<td><img src="/images/settings.png" style='cursor:pointer;' onClick="editRow(<?=$employee->id;?>);"></td>
 			</tr>
 			<tr id='edit_row_<?=$employee->id;?>' style='display:none;'>
 				<td colspan='7' style='padding:0;'>
 							<form method='post' action='' autocomplete='off' id='form_<?=$employee->id;?>'>
 							
 							
						 			<table style='width:100%;'>
						 			<tr >
						 			
								 				<td>
								 				First:<br /><input type='text' name='firstname' value="<?=$employee->firstname;?>" style='width:120px;'>
								 				
								 				<br />
								 				Last:<br /><input type='text' name='lastname' value="<?=$employee->lastname;?>" style='width:120px;'>
								 				
								 				</td>
								 				<td></td>
								 				<td>
								 				Location:<br />
								 				<select name='location' style='width:100px;'>
												<? foreach($this->locations AS $location){ 
														if($employee->location == $location->id){
															$selected = 'selected';
														} else {
															$selected = '';
														}?>
														<option value="<?=$location->id;?>" <?=$selected;?>><?=$location->name;?></option>
													 <? } ?>
												</select>
								 				
								 				<br />
								 				Position:<br /><input type='text' name='position' value="<?=$employee->position;?>" style='width:120px;'>
								 				
								 				</td>
								 				<td></td>
								 				<td>
									 				Acct #1:<br />
									 				<input type='text' name='account_number' class='account_number' value="<?=$employee->account_number;?>" style='width:250px;'>
									 				<br />
									 				Acct #2:<br />
									 				<input type='text' name='account_number_two' class='account_number_two' value="<?=$employee->account_number_two;?>" style='width:245px;'>
								 				
								 				</td>
								 				<td>								 					
								 					
								 					Title Paid:<br />
									 				<select name='paid'>
														<option value="">Select One</option>
														<option value="Yes" <? if($employee->paid == 'Yes'){ echo "selected"; } ?>>Yes</option>
														<option value="No" <? if($employee->paid == 'No'){ echo "selected"; } ?>>No</option>
													</select>
													<br />
								 					ID:<br />
								 					<input type='text' name='cp_id' class='cp_id' value="<?=$employee->cp_id;?>" style='width:100px;'>
								 					
								 				</td>								 				

								 				<td style='text-align:center;'><img src="/images/check.png" style='cursor:pointer;' onClick="$(this).closest('form').submit();"><br />
								 				<input type='button' value="Cancel" style='font-size:13px; padding:4px;' onClick="$('#edit_row_<?=$employee->id;?>').hide();$('#view_row_<?=$employee->id;?>').show();"></td>
								 				<td><img src="/images/trash.png" style='cursor:pointer;' onClick="trash(<?=$employee->id;?>);"></td>
						 			
						 			</tr>
						 			</table>
						 
						 			<input type='hidden' name='id' value='<?=$employee->id;?>'>
						 			<input type='hidden' class='method' name='method' value='update'>
						 				</form>
						 				<form method='post' action='' id='delete_<?=$employee->id;?>'>
						 					<input type='hidden' name='id' value='<?=$employee->id;?>'>
						 					<input type='hidden' class='method' name='method' value='delete'>
						 				</form>
 				</td>
 			</tr><tr></tr>
 			
 		<? } ?>
 	</table>
 
  <?= $this->paginationControl($this->employees, 'Sliding', 'pagination_control.phtml'); ?>
  
  <script type='text/javascript'>
  	$('.jqAccount').each(function(){
		var value = $(this).html();
		$(this).html(format_number(value));
	});

  	$('.account_number').each(function(){
		var va = $(this).val();			
		$(this).val(format_number(va));
	});

  	$('.account_number_two').each(function(){
		var va = $(this).val();			
		$(this).val(format_number(va));
	});
	
  	$(function(){
  		$(".account_number").keyup(function() {
		  var text = $(this).val();
		  var account_number = format_number(text);
		  $('.account_number').val(account_number);		  
		});
  	});

  	$(function(){
  		$(".account_number_two").keyup(function() {
  			var text = $(this).val();
    		var account_number = format_number(text);
    		$('.account_number_two').val(account_number);
  		});
  	});
  
	function editRow(id){
		$('#view_row_'+id).hide();
		$('#edit_row_'+id).slideDown();
	}
	

	function trash(id){
		var sure = confirm("Delete this employee? This cannot be undone.");
		if(sure){
			$('#delete_'+id).submit();
		} else {
			return false;
		}
	}

	function format_number(text)
	{
		var text = text.split("-").join(""); // remove hyphens
		var letters = text.split("");
		var account_number = letters[0];
	  	if(letters[1] != undefined){ account_number = account_number+"-"+letters[1] }
	    if(letters[2] != undefined){ account_number = account_number+letters[2] }
	    if(letters[3] != undefined){ account_number = account_number+letters[3] }
	    if(letters[4] != undefined){ account_number = account_number+"-"+letters[4] }
	    if(letters[5] != undefined){ account_number = account_number+"-"+letters[5] }
	    if(letters[6] != undefined){ account_number = account_number+letters[6] }
	    if(letters[7] != undefined){ account_number = account_number+letters[7] }
	    if(letters[8] != undefined){ account_number = account_number+letters[8] }
	    if(letters[9] != undefined){ account_number = account_number+"-"+letters[9] }
	    if(letters[10] != undefined){ account_number = account_number+letters[10] }
	    if(letters[11] != undefined){ account_number = account_number+letters[11] }
	    if(letters[12] != undefined){ account_number = account_number+letters[12] }
	    if(letters[13] != undefined){ account_number = account_number+"-"+letters[13] }
	    if(letters[14] != undefined){ account_number = account_number+letters[14] }
	    if(letters[15] != undefined){ account_number = account_number+letters[15] }
	    if(letters[16] != undefined){ account_number = account_number+letters[16] }
	    if(letters[17] != undefined){ account_number = account_number+letters[17] }
	    if(letters[18] != undefined){ account_number = account_number+"-"+letters[18] }
	    if(letters[19] != undefined){ account_number = account_number+letters[19] }
	    if(letters[20] != undefined){ account_number = account_number+letters[20] }
	    if(letters[21] != undefined){ account_number = account_number+letters[21] }
	    if(letters[22] != undefined){ account_number = account_number+"-"+letters[22] }
	    
		return account_number;
	}
</script>
