<div class='toolbar' style='height:auto !important;'>
	<h1>New Location</h1>
	<form method='post' action='' autocomplete='off'>
	<table>
		<tr>
			<td>Name</td><td><input type='text' name='name' style='width:200px;' value="<?=@$this->data['name'];?>"></td>

		</tr>
		
	</table>
	<br />
	<input type='hidden' name='method' value='create'>
	<input type='submit' value="Create Location">
	
	</form>
</div>



 <?= $this->paginationControl($this->locations, 'Sliding', 'pagination_control.phtml'); ?>
 	<table class='zebra'>
 		<tr style='background:#000; color:#fff;'>
 			<td>Name</td>

 			<td>Edit</td>
 		</tr>
 		<? foreach($this->locations AS $location){ ?>
 			<tr id='view_row_<?=$location->id;?>'>
 				<td><?=$location->name;?></td>

 				<td><img src="/images/settings.png" style='cursor:pointer;' onClick="editRow(<?=$location->id;?>);"></td>
 			</tr>
 			<tr id='edit_row_<?=$location->id;?>' style='display:none;'>
 				<td colspan='5' style='padding:0;'>
 							<form method='post' action='' autocomplete='off' id='form_<?=$location->id;?>'>
						 			<table>
						 			<tr >
						 			
								 				<td>Name:<br /><input type='text' name='name' value="<?=$location->name;?>" style='width:420px;'></td>
								 			
								 				<td style='text-align:center;'><img src="/images/check.png" style='cursor:pointer;' onClick="$(this).closest('form').submit();"><br />
								 				<input type='button' value="Cancel" style='font-size:13px; padding:4px;' onClick="$('#edit_row_<?=$location->id;?>').hide();$('#view_row_<?=$location->id;?>').show();"></td>
								 				<td><img src="/images/trash.png" style='cursor:pointer;' onClick="trash(<?=$location->id;?>);"></td>
						 			
						 			</tr>
						 			</table>
						 			<input type='hidden' name='id' value='<?=$location->id;?>'>
						 			<input type='hidden' class='method' name='method' value='update'>
						 				</form>
						 				<form method='post' action='' id='delete_<?=$location->id;?>'>
						 					<input type='hidden' name='id' value='<?=$location->id;?>'>
						 					<input type='hidden' class='method' name='method' value='delete'>
						 				</form>
 				</td>
 			</tr><tr></tr>
 			
 		<? } ?>
 	</table>
 
  <?= $this->paginationControl($this->locations, 'Sliding', 'pagination_control.phtml'); ?>
  
  <script type='text/javascript'>
	function editRow(id){
		$('#view_row_'+id).hide();
		$('#edit_row_'+id).slideDown();
	}
	

	function trash(id){
		var sure = confirm("Delete this location? This cannot be undone.");
		if(sure){
			$('#delete_'+id).submit();
		} else {
			return false;
		}
	}

</script	>
